start_msg: |
      ุจุฑุง ุงูฺฉู ุงุทูุงุนุงุช ููุชุฑุดฺฉู ุฑู ุจุจู ูุงุฒู ฺฉ ุงุฒ ููุงุฑุฏ ุฒุฑ ุฑู ุจูุฑุณุช
      QrCode - UUID - Vless - Vmess - remark
      ุงฺฏ ููุฏูู ฺุฌูุฑ ฺฉ ุงุฒูุงุฑู ุจุฏุณุช ุจุงุฑ ุฑู /what ุจุฒู

help_msg: |
      ูุณุจุช ุจู ุงูฺฉู ฺู ูุฑู ุงูุฒุงุฑ ูุตุจ ุฏุงุฑ ูุฑู ูฺฉูู...
      ุงฺฏ ููุฏูู ฺุฌูุฑ ูพุฏุงุด ฺฉู ุฑู /what ุจุฒู

channel_msg: |
      ฺฉุงุฑุจุฑ ฺฏุฑุงู ูุทูุง ุจุฑุง ุงุณุชูุงุฏู ุงุฒ ุฑุจุงุช ุ ุงุจุชุฏุง ุฏุฑ ฺฉุงูุงู ุฒุฑ ุนุถู ุดูุฏ ๐ 
      ๐ @your_channel_id
      ู ุณูพุณ ุฏูุจุงุฑู ุฏุณุชูุฑ /start ุฑุง ุงุฑุณุงู ฺฉูุฏ

not_found: "<b>๐ุงุทูุงุนุงุช ุงฺฉุงูุช ุดูุง ูพุฏุง ูุดุฏ!</b> \n ูุทูุฆูุฏ <b>QrCode - UUID - Vless - Vmess - remark</b> ุฑู ุฏุฑุณุช ูุงุฑุฏ ฺฉุฑุฏูุ \n ุงฺฏู ููุฏููู ฺุฌูุฑ ฺฉ ุงุฒูุง ุฑู ุจุฏุณุช ุจุงุฑู ุฑู /what ุจุฒูุฏ... \n  ูุณุจุช ุจู ุงูฺฉู ฺู ูุฑู ุงูุฒุงุฑ ูุตุจ ุฏุงุฑู ุจู ุดูุง ฺฉูฺฉ ูฺฉูู."
acc_info: ๐ ุงุทูุงุนุงุช ุณุฑูุณ ุดูุง ุชุง ุงู ูุญุธู ๐
whatapp_msg: ฺู ูุฑู ุงูุฒุงุฑ ุงุณุชูุงุฏู ูฺฉูุฏุ

qrcode: ูุทูุง ููฺฉ ุงฺฉุงูุช ุฑุง ุงุฑุณุงู ฺฉูุฏ
